/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Session = IDL.Variant({
  'ny' : IDL.Null,
  'asia' : IDL.Null,
  'london' : IDL.Null,
});
export const PlaybookEntryId = IDL.Nat;
export const TradeType = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
export const TradeResult = IDL.Variant({
  'be' : IDL.Null,
  'win' : IDL.Null,
  'loss' : IDL.Null,
});
export const TradeId = IDL.Nat;
export const PlaybookEntry = IDL.Record({
  'id' : PlaybookEntryId,
  'poi' : IDL.Text,
  'htfBias' : IDL.Text,
  'owner' : IDL.Principal,
  'createdAt' : IDL.Int,
  'pair' : IDL.Text,
  'liquidityTarget' : IDL.Text,
  'qualityScore' : IDL.Nat,
  'session' : Session,
  'marketStructure' : IDL.Text,
  'rrTarget' : IDL.Float64,
  'entryConfirmation' : IDL.Text,
});
export const Trade = IDL.Record({
  'id' : TradeId,
  'result' : TradeResult,
  'screenshotFileId' : IDL.Opt(IDL.Text),
  'tradeType' : TradeType,
  'emotion' : IDL.Text,
  'owner' : IDL.Principal,
  'date' : IDL.Text,
  'takeProfit' : IDL.Float64,
  'pair' : IDL.Text,
  'rrAchieved' : IDL.Float64,
  'stopLoss' : IDL.Float64,
  'notes' : IDL.Text,
  'entryPrice' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'tradingStyle' : IDL.Text,
  'displayName' : IDL.Text,
  'createdAt' : IDL.Int,
  'accountCurrency' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateAverageRR' : IDL.Func([], [IDL.Float64], ['query']),
  'calculateLongestLossStreak' : IDL.Func([], [IDL.Nat], ['query']),
  'calculateLongestWinStreak' : IDL.Func([], [IDL.Nat], ['query']),
  'calculateWinRate' : IDL.Func([], [IDL.Float64], ['query']),
  'countTradeResults' : IDL.Func([], [IDL.Nat, IDL.Nat, IDL.Nat], ['query']),
  'createPlaybookEntry' : IDL.Func(
      [
        IDL.Text,
        Session,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Nat,
      ],
      [PlaybookEntryId],
      [],
    ),
  'createTrade' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        TradeType,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        TradeResult,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [TradeId],
      [],
    ),
  'deletePlaybookEntry' : IDL.Func([PlaybookEntryId], [], []),
  'deleteTrade' : IDL.Func([TradeId], [], []),
  'getAllPlaybookEntries' : IDL.Func([], [IDL.Vec(PlaybookEntry)], ['query']),
  'getAllTrades' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLosingPairs' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getPlaybookEntry' : IDL.Func([PlaybookEntryId], [PlaybookEntry], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getTrade' : IDL.Func([TradeId], [Trade], ['query']),
  'getTradesByPair' : IDL.Func([IDL.Text], [IDL.Vec(Trade)], ['query']),
  'getTradesByResult' : IDL.Func([TradeResult], [IDL.Vec(Trade)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWinRateByPair' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
  'getWinRateByTradeType' : IDL.Func([TradeType], [IDL.Float64], ['query']),
  'getWinningPairs' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'hasProfile' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'updatePlaybookEntry' : IDL.Func([PlaybookEntry], [], []),
  'updateTrade' : IDL.Func([Trade], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Session = IDL.Variant({
    'ny' : IDL.Null,
    'asia' : IDL.Null,
    'london' : IDL.Null,
  });
  const PlaybookEntryId = IDL.Nat;
  const TradeType = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
  const TradeResult = IDL.Variant({
    'be' : IDL.Null,
    'win' : IDL.Null,
    'loss' : IDL.Null,
  });
  const TradeId = IDL.Nat;
  const PlaybookEntry = IDL.Record({
    'id' : PlaybookEntryId,
    'poi' : IDL.Text,
    'htfBias' : IDL.Text,
    'owner' : IDL.Principal,
    'createdAt' : IDL.Int,
    'pair' : IDL.Text,
    'liquidityTarget' : IDL.Text,
    'qualityScore' : IDL.Nat,
    'session' : Session,
    'marketStructure' : IDL.Text,
    'rrTarget' : IDL.Float64,
    'entryConfirmation' : IDL.Text,
  });
  const Trade = IDL.Record({
    'id' : TradeId,
    'result' : TradeResult,
    'screenshotFileId' : IDL.Opt(IDL.Text),
    'tradeType' : TradeType,
    'emotion' : IDL.Text,
    'owner' : IDL.Principal,
    'date' : IDL.Text,
    'takeProfit' : IDL.Float64,
    'pair' : IDL.Text,
    'rrAchieved' : IDL.Float64,
    'stopLoss' : IDL.Float64,
    'notes' : IDL.Text,
    'entryPrice' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'tradingStyle' : IDL.Text,
    'displayName' : IDL.Text,
    'createdAt' : IDL.Int,
    'accountCurrency' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateAverageRR' : IDL.Func([], [IDL.Float64], ['query']),
    'calculateLongestLossStreak' : IDL.Func([], [IDL.Nat], ['query']),
    'calculateLongestWinStreak' : IDL.Func([], [IDL.Nat], ['query']),
    'calculateWinRate' : IDL.Func([], [IDL.Float64], ['query']),
    'countTradeResults' : IDL.Func([], [IDL.Nat, IDL.Nat, IDL.Nat], ['query']),
    'createPlaybookEntry' : IDL.Func(
        [
          IDL.Text,
          Session,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Nat,
        ],
        [PlaybookEntryId],
        [],
      ),
    'createTrade' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          TradeType,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          TradeResult,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [TradeId],
        [],
      ),
    'deletePlaybookEntry' : IDL.Func([PlaybookEntryId], [], []),
    'deleteTrade' : IDL.Func([TradeId], [], []),
    'getAllPlaybookEntries' : IDL.Func([], [IDL.Vec(PlaybookEntry)], ['query']),
    'getAllTrades' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLosingPairs' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getPlaybookEntry' : IDL.Func(
        [PlaybookEntryId],
        [PlaybookEntry],
        ['query'],
      ),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getTrade' : IDL.Func([TradeId], [Trade], ['query']),
    'getTradesByPair' : IDL.Func([IDL.Text], [IDL.Vec(Trade)], ['query']),
    'getTradesByResult' : IDL.Func([TradeResult], [IDL.Vec(Trade)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWinRateByPair' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
    'getWinRateByTradeType' : IDL.Func([TradeType], [IDL.Float64], ['query']),
    'getWinningPairs' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'hasProfile' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'updatePlaybookEntry' : IDL.Func([PlaybookEntry], [], []),
    'updateTrade' : IDL.Func([Trade], [], []),
  });
};

export const init = ({ IDL }) => { return []; };