/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PlaybookEntry {
  'id' : PlaybookEntryId,
  'poi' : string,
  'htfBias' : string,
  'owner' : Principal,
  'createdAt' : bigint,
  'pair' : string,
  'liquidityTarget' : string,
  'qualityScore' : bigint,
  'session' : Session,
  'marketStructure' : string,
  'rrTarget' : number,
  'entryConfirmation' : string,
}
export type PlaybookEntryId = bigint;
export type Session = { 'ny' : null } |
  { 'asia' : null } |
  { 'london' : null };
export interface Trade {
  'id' : TradeId,
  'result' : TradeResult,
  'screenshotFileId' : [] | [string],
  'tradeType' : TradeType,
  'emotion' : string,
  'owner' : Principal,
  'date' : string,
  'takeProfit' : number,
  'pair' : string,
  'rrAchieved' : number,
  'stopLoss' : number,
  'notes' : string,
  'entryPrice' : number,
}
export type TradeId = bigint;
export type TradeResult = { 'be' : null } |
  { 'win' : null } |
  { 'loss' : null };
export type TradeType = { 'buy' : null } |
  { 'sell' : null };
export interface UserProfile {
  'bio' : string,
  'tradingStyle' : string,
  'displayName' : string,
  'createdAt' : bigint,
  'accountCurrency' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateAverageRR' : ActorMethod<[], number>,
  'calculateLongestLossStreak' : ActorMethod<[], bigint>,
  'calculateLongestWinStreak' : ActorMethod<[], bigint>,
  'calculateWinRate' : ActorMethod<[], number>,
  'countTradeResults' : ActorMethod<[], [bigint, bigint, bigint]>,
  'createPlaybookEntry' : ActorMethod<
    [string, Session, string, string, string, string, string, number, bigint],
    PlaybookEntryId
  >,
  'createTrade' : ActorMethod<
    [
      string,
      string,
      TradeType,
      number,
      number,
      number,
      number,
      TradeResult,
      string,
      string,
      [] | [string],
    ],
    TradeId
  >,
  'deletePlaybookEntry' : ActorMethod<[PlaybookEntryId], undefined>,
  'deleteTrade' : ActorMethod<[TradeId], undefined>,
  'getAllPlaybookEntries' : ActorMethod<[], Array<PlaybookEntry>>,
  'getAllTrades' : ActorMethod<[], Array<Trade>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLosingPairs' : ActorMethod<[], Array<string>>,
  'getPlaybookEntry' : ActorMethod<[PlaybookEntryId], PlaybookEntry>,
  'getProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getTrade' : ActorMethod<[TradeId], Trade>,
  'getTradesByPair' : ActorMethod<[string], Array<Trade>>,
  'getTradesByResult' : ActorMethod<[TradeResult], Array<Trade>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWinRateByPair' : ActorMethod<[string], number>,
  'getWinRateByTradeType' : ActorMethod<[TradeType], number>,
  'getWinningPairs' : ActorMethod<[], Array<string>>,
  'hasProfile' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveProfile' : ActorMethod<[string, string, string, string], undefined>,
  'updatePlaybookEntry' : ActorMethod<[PlaybookEntry], undefined>,
  'updateTrade' : ActorMethod<[Trade], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];