/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type TradeTime = string;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type TradeId = bigint;
export interface Trade {
    id: TradeId;
    result: TradeResult;
    screenshotFileId?: string;
    tradeTime: TradeTime;
    tradeType: TradeType;
    emotion: string;
    owner: Principal;
    date: string;
    takeProfit: number;
    pair: string;
    rrAchieved: number;
    stopLoss: number;
    notes: string;
    entryTimeframe: Timeframe;
    entryPrice: number;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface PlaybookEntry {
    id: PlaybookEntryId;
    poi: string;
    htfBias: string;
    owner: Principal;
    createdAt: bigint;
    pair: string;
    liquidityTarget: string;
    qualityScore: bigint;
    session: Session;
    marketStructure: string;
    rrTarget: number;
    entryConfirmation: string;
}
export type Timeframe = string;
export interface UserProfile {
    bio: string;
    tradingStyle: string;
    displayName: string;
    createdAt: bigint;
    accountCurrency: string;
}
export type PlaybookEntryId = bigint;
export enum Session {
    ny = "ny",
    asia = "asia",
    london = "london"
}
export enum TradeResult {
    be = "be",
    win = "win",
    loss = "loss"
}
export enum TradeType {
    buy = "buy",
    sell = "sell"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    calculateAverageRR(): Promise<number>;
    calculateLongestLossStreak(): Promise<bigint>;
    calculateLongestWinStreak(): Promise<bigint>;
    calculateWinRate(): Promise<number>;
    countTradeResults(): Promise<[bigint, bigint, bigint]>;
    createPlaybookEntry(pair: string, session: Session, htfBias: string, marketStructure: string, liquidityTarget: string, poi: string, entryConfirmation: string, rrTarget: number, qualityScore: bigint): Promise<PlaybookEntryId>;
    createTrade(date: string, pair: string, tradeType: TradeType, entryPrice: number, stopLoss: number, takeProfit: number, rrAchieved: number, result: TradeResult, emotion: string, notes: string, screenshotFileId: string | null, entryTimeframe: Timeframe, tradeTime: TradeTime): Promise<TradeId>;
    deletePlaybookEntry(id: PlaybookEntryId): Promise<void>;
    deleteTrade(id: TradeId): Promise<void>;
    getAllPlaybookEntries(): Promise<Array<PlaybookEntry>>;
    getAllTrades(): Promise<Array<Trade>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getLosingPairs(): Promise<Array<string>>;
    getPlaybookEntry(id: PlaybookEntryId): Promise<PlaybookEntry>;
    getProfile(): Promise<UserProfile | null>;
    getTrade(id: TradeId): Promise<Trade>;
    getTradesByPair(pair: string): Promise<Array<Trade>>;
    getTradesByResult(result: TradeResult): Promise<Array<Trade>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWinRateByPair(pair: string): Promise<number>;
    getWinRateByTradeType(tradeType: TradeType): Promise<number>;
    getWinningPairs(): Promise<Array<string>>;
    hasProfile(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveProfile(displayName: string, tradingStyle: string, accountCurrency: string, bio: string): Promise<void>;
    updatePlaybookEntry(entry: PlaybookEntry): Promise<void>;
    updateTrade(trade: Trade): Promise<void>;
}
import type { PlaybookEntry as _PlaybookEntry, PlaybookEntryId as _PlaybookEntryId, Session as _Session, Timeframe as _Timeframe, Trade as _Trade, TradeId as _TradeId, TradeResult as _TradeResult, TradeTime as _TradeTime, TradeType as _TradeType, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async calculateAverageRR(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateAverageRR();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateAverageRR();
            return result;
        }
    }
    async calculateLongestLossStreak(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateLongestLossStreak();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateLongestLossStreak();
            return result;
        }
    }
    async calculateLongestWinStreak(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateLongestWinStreak();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateLongestWinStreak();
            return result;
        }
    }
    async calculateWinRate(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateWinRate();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateWinRate();
            return result;
        }
    }
    async countTradeResults(): Promise<[bigint, bigint, bigint]> {
        if (this.processError) {
            try {
                const result = await this.actor.countTradeResults();
                return [
                    result[0],
                    result[1],
                    result[2]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.countTradeResults();
            return [
                result[0],
                result[1],
                result[2]
            ];
        }
    }
    async createPlaybookEntry(arg0: string, arg1: Session, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: number, arg8: bigint): Promise<PlaybookEntryId> {
        if (this.processError) {
            try {
                const result = await this.actor.createPlaybookEntry(arg0, to_candid_Session_n10(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPlaybookEntry(arg0, to_candid_Session_n10(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async createTrade(arg0: string, arg1: string, arg2: TradeType, arg3: number, arg4: number, arg5: number, arg6: number, arg7: TradeResult, arg8: string, arg9: string, arg10: string | null, arg11: Timeframe, arg12: TradeTime): Promise<TradeId> {
        if (this.processError) {
            try {
                const result = await this.actor.createTrade(arg0, arg1, to_candid_TradeType_n12(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, to_candid_TradeResult_n14(this._uploadFile, this._downloadFile, arg7), arg8, arg9, to_candid_opt_n16(this._uploadFile, this._downloadFile, arg10), arg11, arg12);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTrade(arg0, arg1, to_candid_TradeType_n12(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, to_candid_TradeResult_n14(this._uploadFile, this._downloadFile, arg7), arg8, arg9, to_candid_opt_n16(this._uploadFile, this._downloadFile, arg10), arg11, arg12);
            return result;
        }
    }
    async deletePlaybookEntry(arg0: PlaybookEntryId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePlaybookEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePlaybookEntry(arg0);
            return result;
        }
    }
    async deleteTrade(arg0: TradeId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTrade(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTrade(arg0);
            return result;
        }
    }
    async getAllPlaybookEntries(): Promise<Array<PlaybookEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlaybookEntries();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlaybookEntries();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTrades(): Promise<Array<Trade>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTrades();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTrades();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLosingPairs(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLosingPairs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLosingPairs();
            return result;
        }
    }
    async getPlaybookEntry(arg0: PlaybookEntryId): Promise<PlaybookEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlaybookEntry(arg0);
                return from_candid_PlaybookEntry_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlaybookEntry(arg0);
            return from_candid_PlaybookEntry_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrade(arg0: TradeId): Promise<Trade> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrade(arg0);
                return from_candid_Trade_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrade(arg0);
            return from_candid_Trade_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTradesByPair(arg0: string): Promise<Array<Trade>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradesByPair(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradesByPair(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTradesByResult(arg0: TradeResult): Promise<Array<Trade>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradesByResult(to_candid_TradeResult_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradesByResult(to_candid_TradeResult_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWinRateByPair(arg0: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getWinRateByPair(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWinRateByPair(arg0);
            return result;
        }
    }
    async getWinRateByTradeType(arg0: TradeType): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getWinRateByTradeType(to_candid_TradeType_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWinRateByTradeType(to_candid_TradeType_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getWinningPairs(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWinningPairs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWinningPairs();
            return result;
        }
    }
    async hasProfile(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasProfile();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveProfile(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProfile(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProfile(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updatePlaybookEntry(arg0: PlaybookEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlaybookEntry(to_candid_PlaybookEntry_n33(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlaybookEntry(to_candid_PlaybookEntry_n33(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateTrade(arg0: Trade): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTrade(to_candid_Trade_n35(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTrade(to_candid_Trade_n35(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_PlaybookEntry_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlaybookEntry): PlaybookEntry {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Session_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Session): Session {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_TradeResult_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeResult): TradeResult {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_TradeType_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeType): TradeType {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Trade_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Trade): Trade {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PlaybookEntryId;
    poi: string;
    htfBias: string;
    owner: Principal;
    createdAt: bigint;
    pair: string;
    liquidityTarget: string;
    qualityScore: bigint;
    session: _Session;
    marketStructure: string;
    rrTarget: number;
    entryConfirmation: string;
}): {
    id: PlaybookEntryId;
    poi: string;
    htfBias: string;
    owner: Principal;
    createdAt: bigint;
    pair: string;
    liquidityTarget: string;
    qualityScore: bigint;
    session: Session;
    marketStructure: string;
    rrTarget: number;
    entryConfirmation: string;
} {
    return {
        id: value.id,
        poi: value.poi,
        htfBias: value.htfBias,
        owner: value.owner,
        createdAt: value.createdAt,
        pair: value.pair,
        liquidityTarget: value.liquidityTarget,
        qualityScore: value.qualityScore,
        session: from_candid_Session_n20(_uploadFile, _downloadFile, value.session),
        marketStructure: value.marketStructure,
        rrTarget: value.rrTarget,
        entryConfirmation: value.entryConfirmation
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TradeId;
    result: _TradeResult;
    screenshotFileId: [] | [string];
    tradeTime: _TradeTime;
    tradeType: _TradeType;
    emotion: string;
    owner: Principal;
    date: string;
    takeProfit: number;
    pair: string;
    rrAchieved: number;
    stopLoss: number;
    notes: string;
    entryTimeframe: _Timeframe;
    entryPrice: number;
}): {
    id: TradeId;
    result: TradeResult;
    screenshotFileId?: string;
    tradeTime: TradeTime;
    tradeType: TradeType;
    emotion: string;
    owner: Principal;
    date: string;
    takeProfit: number;
    pair: string;
    rrAchieved: number;
    stopLoss: number;
    notes: string;
    entryTimeframe: Timeframe;
    entryPrice: number;
} {
    return {
        id: value.id,
        result: from_candid_TradeResult_n25(_uploadFile, _downloadFile, value.result),
        screenshotFileId: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.screenshotFileId)),
        tradeTime: value.tradeTime,
        tradeType: from_candid_TradeType_n28(_uploadFile, _downloadFile, value.tradeType),
        emotion: value.emotion,
        owner: value.owner,
        date: value.date,
        takeProfit: value.takeProfit,
        pair: value.pair,
        rrAchieved: value.rrAchieved,
        stopLoss: value.stopLoss,
        notes: value.notes,
        entryTimeframe: value.entryTimeframe,
        entryPrice: value.entryPrice
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ny: null;
} | {
    asia: null;
} | {
    london: null;
}): Session {
    return "ny" in value ? Session.ny : "asia" in value ? Session.asia : "london" in value ? Session.london : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    be: null;
} | {
    win: null;
} | {
    loss: null;
}): TradeResult {
    return "be" in value ? TradeResult.be : "win" in value ? TradeResult.win : "loss" in value ? TradeResult.loss : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    sell: null;
}): TradeType {
    return "buy" in value ? TradeType.buy : "sell" in value ? TradeType.sell : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PlaybookEntry>): Array<PlaybookEntry> {
    return value.map((x)=>from_candid_PlaybookEntry_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Trade>): Array<Trade> {
    return value.map((x)=>from_candid_Trade_n23(_uploadFile, _downloadFile, x));
}
function to_candid_PlaybookEntry_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlaybookEntry): _PlaybookEntry {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_Session_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Session): _Session {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_TradeResult_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeResult): _TradeResult {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_TradeType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeType): _TradeType {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_Trade_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Trade): _Trade {
    return to_candid_record_n36(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: PlaybookEntryId;
    poi: string;
    htfBias: string;
    owner: Principal;
    createdAt: bigint;
    pair: string;
    liquidityTarget: string;
    qualityScore: bigint;
    session: Session;
    marketStructure: string;
    rrTarget: number;
    entryConfirmation: string;
}): {
    id: _PlaybookEntryId;
    poi: string;
    htfBias: string;
    owner: Principal;
    createdAt: bigint;
    pair: string;
    liquidityTarget: string;
    qualityScore: bigint;
    session: _Session;
    marketStructure: string;
    rrTarget: number;
    entryConfirmation: string;
} {
    return {
        id: value.id,
        poi: value.poi,
        htfBias: value.htfBias,
        owner: value.owner,
        createdAt: value.createdAt,
        pair: value.pair,
        liquidityTarget: value.liquidityTarget,
        qualityScore: value.qualityScore,
        session: to_candid_Session_n10(_uploadFile, _downloadFile, value.session),
        marketStructure: value.marketStructure,
        rrTarget: value.rrTarget,
        entryConfirmation: value.entryConfirmation
    };
}
function to_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: TradeId;
    result: TradeResult;
    screenshotFileId?: string;
    tradeTime: TradeTime;
    tradeType: TradeType;
    emotion: string;
    owner: Principal;
    date: string;
    takeProfit: number;
    pair: string;
    rrAchieved: number;
    stopLoss: number;
    notes: string;
    entryTimeframe: Timeframe;
    entryPrice: number;
}): {
    id: _TradeId;
    result: _TradeResult;
    screenshotFileId: [] | [string];
    tradeTime: _TradeTime;
    tradeType: _TradeType;
    emotion: string;
    owner: Principal;
    date: string;
    takeProfit: number;
    pair: string;
    rrAchieved: number;
    stopLoss: number;
    notes: string;
    entryTimeframe: _Timeframe;
    entryPrice: number;
} {
    return {
        id: value.id,
        result: to_candid_TradeResult_n14(_uploadFile, _downloadFile, value.result),
        screenshotFileId: value.screenshotFileId ? candid_some(value.screenshotFileId) : candid_none(),
        tradeTime: value.tradeTime,
        tradeType: to_candid_TradeType_n12(_uploadFile, _downloadFile, value.tradeType),
        emotion: value.emotion,
        owner: value.owner,
        date: value.date,
        takeProfit: value.takeProfit,
        pair: value.pair,
        rrAchieved: value.rrAchieved,
        stopLoss: value.stopLoss,
        notes: value.notes,
        entryTimeframe: value.entryTimeframe,
        entryPrice: value.entryPrice
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Session): {
    ny: null;
} | {
    asia: null;
} | {
    london: null;
} {
    return value == Session.ny ? {
        ny: null
    } : value == Session.asia ? {
        asia: null
    } : value == Session.london ? {
        london: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeType): {
    buy: null;
} | {
    sell: null;
} {
    return value == TradeType.buy ? {
        buy: null
    } : value == TradeType.sell ? {
        sell: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeResult): {
    be: null;
} | {
    win: null;
} | {
    loss: null;
} {
    return value == TradeResult.be ? {
        be: null
    } : value == TradeResult.win ? {
        win: null
    } : value == TradeResult.loss ? {
        loss: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
